base_url = "http://localhost:8000"

[owner]
owner_name = ""
owner_email = ""

[database]
url = ""

[auth]
google_client_id = ""
google_client_secret = ""

naver_client_id = ""
naver_client_secret = ""